services:
  db:
    image: postgres:16.1-alpine
    container_name: whatever-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=whatever-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5450:5432"
    volumes:
      - whatever_db_pg_data:/var/lib/postgresql/data

volumes:
  whatever_db_pg_data: